uploads = []
generated = []

[[outputs]]
id = "MqzqE3OcjJ-pT3XRmkK_m"
uri = "file://api/docs/openapi.json"
type = "unspecified"
title = "Bina Academy API — OpenAPI JSON"

[[outputs]]
id = "YY8KlGR6cC5S4hD1Xboqs"
uri = "file://bina-academy-api.postman_collection.json"
type = "unspecified"
title = "Bina Academy API — Postman Collection"
